// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package fueleconomy

// KilometrePerLitre (Kilometre Per Litre) conversion functions
type KilometrePerLitre float64

// ToUSMilesPerGallon converts the supplied Kilometre Per Litre value to US Miles Per Gallon
func (value KilometrePerLitre) ToUSMilesPerGallon() float64 { 
	return float64(value * 2.35215)
}
// ToMilesPerGallon converts the supplied Kilometre Per Litre value to Miles Per Gallon
func (value KilometrePerLitre) ToMilesPerGallon() float64 { 
	return float64(value * 2.82481)
}
// ToLitresPer100Kilometres converts the supplied Kilometre Per Litre value to Litres Per 100 Kilometres
func (value KilometrePerLitre) ToLitresPer100Kilometres() float64 { 
	return float64(100.0 / value)
}

// LitresPer100Kilometres (Litres Per 100 Kilometres) conversion functions
type LitresPer100Kilometres float64

// ToKilometrePerLitre converts the supplied Litres Per 100 Kilometres value to Kilometre Per Litre
func (value LitresPer100Kilometres) ToKilometrePerLitre() float64 { 
	return float64(100.0 / value)
}
// ToMilesPerGallon converts the supplied Litres Per 100 Kilometres value to Miles Per Gallon
func (value LitresPer100Kilometres) ToMilesPerGallon() float64 { 
	return float64(282.481 / value)
}
// ToUSMilesPerGallon converts the supplied Litres Per 100 Kilometres value to US Miles Per Gallon
func (value LitresPer100Kilometres) ToUSMilesPerGallon() float64 { 
	return float64(235.215 / value)
}

// MilesPerGallon (Miles Per Gallon) conversion functions
type MilesPerGallon float64

// ToKilometrePerLitre converts the supplied Miles Per Gallon value to Kilometre Per Litre
func (value MilesPerGallon) ToKilometrePerLitre() float64 { 
	return float64(value / 2.82481)
}
// ToUSMilesPerGallon converts the supplied Miles Per Gallon value to US Miles Per Gallon
func (value MilesPerGallon) ToUSMilesPerGallon() float64 { 
	return float64(value / 1.20095)
}
// ToLitresPer100Kilometres converts the supplied Miles Per Gallon value to Litres Per 100 Kilometres
func (value MilesPerGallon) ToLitresPer100Kilometres() float64 { 
	return float64(282.481 / value)
}

// USMilesPerGallon (US Miles Per Gallon) conversion functions
type USMilesPerGallon float64

// ToKilometrePerLitre converts the supplied US Miles Per Gallon value to Kilometre Per Litre
func (value USMilesPerGallon) ToKilometrePerLitre() float64 { 
	return float64(value / 2.35215)
}
// ToMilesPerGallon converts the supplied US Miles Per Gallon value to Miles Per Gallon
func (value USMilesPerGallon) ToMilesPerGallon() float64 { 
	return float64(value * 1.20095)
}
// ToLitresPer100Kilometres converts the supplied US Miles Per Gallon value to Litres Per 100 Kilometres
func (value USMilesPerGallon) ToLitresPer100Kilometres() float64 { 
	return float64(235.215 / value)
}
