// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package data_transfer_rate

/// Bits Per Second conversion functions
type BitsPerSecond float64

/// Converts the supplied Bits Per Second value to KiloBits Per Second
func (value BitsPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Bits Per Second value to MegaBits Per Second
func (value BitsPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied Bits Per Second value to GigaBits Per Second
func (value BitsPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 1e+9)
}
/// Converts the supplied Bits Per Second value to TeraBits Per Second
func (value BitsPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 1e+12)
}
/// Converts the supplied Bits Per Second value to KiloBytes Per Second
func (value BitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value / 8000.0)
}
/// Converts the supplied Bits Per Second value to MegaBytes Per Second
func (value BitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value / 8e+6)
}
/// Converts the supplied Bits Per Second value to GigaBytes Per Second
func (value BitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 8e+9)
}
/// Converts the supplied Bits Per Second value to TeraBytes Per Second
func (value BitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 8e+12)
}
/// Converts the supplied Bits Per Second value to Kibibits Per Second
func (value BitsPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value / 1024.0)
}
/// Converts the supplied Bits Per Second value to Mebibits Per Second
func (value BitsPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value / 1048576.0)
}

/// GigaBits Per Second conversion functions
type GigaBitsPerSecond float64

/// Converts the supplied GigaBits Per Second value to Bits Per Second
func (value GigaBitsPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 1e+9)
}
/// Converts the supplied GigaBits Per Second value to KiloBits Per Second
func (value GigaBitsPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied GigaBits Per Second value to MegaBits Per Second
func (value GigaBitsPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied GigaBits Per Second value to TeraBits Per Second
func (value GigaBitsPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied GigaBits Per Second value to KiloBytes Per Second
func (value GigaBitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value * 125000.0)
}
/// Converts the supplied GigaBits Per Second value to MegaBytes Per Second
func (value GigaBitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value * 125.0)
}
/// Converts the supplied GigaBits Per Second value to GigaBytes Per Second
func (value GigaBitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 8.0)
}
/// Converts the supplied GigaBits Per Second value to TeraBytes Per Second
func (value GigaBitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 8000.0)
}
/// Converts the supplied GigaBits Per Second value to Kibibits Per Second
func (value GigaBitsPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 976562.5)
}
/// Converts the supplied GigaBits Per Second value to Mebibits Per Second
func (value GigaBitsPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value * 953.67431640625)
}

/// GigaBytes Per Second conversion functions
type GigaBytesPerSecond float64

/// Converts the supplied GigaBytes Per Second value to Bits Per Second
func (value GigaBytesPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 8e+9)
}
/// Converts the supplied GigaBytes Per Second value to KiloBits Per Second
func (value GigaBytesPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 8e+6)
}
/// Converts the supplied GigaBytes Per Second value to MegaBits Per Second
func (value GigaBytesPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value * 8000.0)
}
/// Converts the supplied GigaBytes Per Second value to GigaBits Per Second
func (value GigaBytesPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value * 8.0)
}
/// Converts the supplied GigaBytes Per Second value to TeraBits Per Second
func (value GigaBytesPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 125.0)
}
/// Converts the supplied GigaBytes Per Second value to KiloBytes Per Second
func (value GigaBytesPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied GigaBytes Per Second value to MegaBytes Per Second
func (value GigaBytesPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied GigaBytes Per Second value to TeraBytes Per Second
func (value GigaBytesPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied GigaBytes Per Second value to Kibibits Per Second
func (value GigaBytesPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 7812500.0)
}
/// Converts the supplied GigaBytes Per Second value to Mebibits Per Second
func (value GigaBytesPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value * 7629.39)
}

/// Kibibits Per Second conversion functions
type KibibitsPerSecond float64

/// Converts the supplied Kibibits Per Second value to Bits Per Second
func (value KibibitsPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 1024.0)
}
/// Converts the supplied Kibibits Per Second value to KiloBits Per Second
func (value KibibitsPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 1.024)
}
/// Converts the supplied Kibibits Per Second value to MegaBits Per Second
func (value KibibitsPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value / 976.563)
}
/// Converts the supplied Kibibits Per Second value to GigaBits Per Second
func (value KibibitsPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 976562.5)
}
/// Converts the supplied Kibibits Per Second value to TeraBits Per Second
func (value KibibitsPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 976562500.0)
}
/// Converts the supplied Kibibits Per Second value to KiloBytes Per Second
func (value KibibitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value / 7.8125)
}
/// Converts the supplied Kibibits Per Second value to MegaBytes Per Second
func (value KibibitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value / 7812.5)
}
/// Converts the supplied Kibibits Per Second value to GigaBytes Per Second
func (value KibibitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 7812500.0)
}
/// Converts the supplied Kibibits Per Second value to TeraBytes Per Second
func (value KibibitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 7812500000.0)
}
/// Converts the supplied Kibibits Per Second value to Mebibits Per Second
func (value KibibitsPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value / 1024.0)
}

/// KiloBits Per Second conversion functions
type KiloBitsPerSecond float64

/// Converts the supplied KiloBits Per Second value to Bits Per Second
func (value KiloBitsPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied KiloBits Per Second value to MegaBits Per Second
func (value KiloBitsPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied KiloBits Per Second value to GigaBits Per Second
func (value KiloBitsPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied KiloBits Per Second value to TeraBits Per Second
func (value KiloBitsPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 1e+9)
}
/// Converts the supplied KiloBits Per Second value to KiloBytes Per Second
func (value KiloBitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value / 8.0)
}
/// Converts the supplied KiloBits Per Second value to MegaBytes Per Second
func (value KiloBitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value / 8000.0)
}
/// Converts the supplied KiloBits Per Second value to GigaBytes Per Second
func (value KiloBitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 8e+6)
}
/// Converts the supplied KiloBits Per Second value to TeraBytes Per Second
func (value KiloBitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 8e+9)
}
/// Converts the supplied KiloBits Per Second value to Kibibits Per Second
func (value KiloBitsPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value / 1.024)
}
/// Converts the supplied KiloBits Per Second value to Mebibits Per Second
func (value KiloBitsPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value / 1048.58)
}

/// KiloBytes Per Second conversion functions
type KiloBytesPerSecond float64

/// Converts the supplied KiloBytes Per Second value to Bits Per Second
func (value KiloBytesPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 8000.0)
}
/// Converts the supplied KiloBytes Per Second value to KiloBits Per Second
func (value KiloBytesPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 8.0)
}
/// Converts the supplied KiloBytes Per Second value to MegaBits Per Second
func (value KiloBytesPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value / 125.0)
}
/// Converts the supplied KiloBytes Per Second value to GigaBits Per Second
func (value KiloBytesPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 125000.0)
}
/// Converts the supplied KiloBytes Per Second value to TeraBits Per Second
func (value KiloBytesPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 1.25e+8)
}
/// Converts the supplied KiloBytes Per Second value to MegaBytes Per Second
func (value KiloBytesPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied KiloBytes Per Second value to GigaBytes Per Second
func (value KiloBytesPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied KiloBytes Per Second value to TeraBytes Per Second
func (value KiloBytesPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 1e+9)
}
/// Converts the supplied KiloBytes Per Second value to Kibibits Per Second
func (value KiloBytesPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 7.8125)
}
/// Converts the supplied KiloBytes Per Second value to Mebibits Per Second
func (value KiloBytesPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value * 0.00762939)
}

/// Mebibits Per Second conversion functions
type MebibitsPerSecond float64

/// Converts the supplied Mebibits Per Second value to Bits Per Second
func (value MebibitsPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 1048576.0)
}
/// Converts the supplied Mebibits Per Second value to KiloBits Per Second
func (value MebibitsPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 1048.58)
}
/// Converts the supplied Mebibits Per Second value to MegaBits Per Second
func (value MebibitsPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value * 1.04858)
}
/// Converts the supplied Mebibits Per Second value to GigaBits Per Second
func (value MebibitsPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 953.67431640625)
}
/// Converts the supplied Mebibits Per Second value to TeraBits Per Second
func (value MebibitsPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 953674.0)
}
/// Converts the supplied Mebibits Per Second value to KiloBytes Per Second
func (value MebibitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value / 0.00762939)
}
/// Converts the supplied Mebibits Per Second value to MegaBytes Per Second
func (value MebibitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value / 7.62939)
}
/// Converts the supplied Mebibits Per Second value to GigaBytes Per Second
func (value MebibitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 7629.39)
}
/// Converts the supplied Mebibits Per Second value to TeraBytes Per Second
func (value MebibitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value * 0.000000131072)
}
/// Converts the supplied Mebibits Per Second value to Kibibits Per Second
func (value MebibitsPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 1024.0)
}

/// MegaBits Per Second conversion functions
type MegaBitsPerSecond float64

/// Converts the supplied MegaBits Per Second value to Bits Per Second
func (value MegaBitsPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied MegaBits Per Second value to KiloBits Per Second
func (value MegaBitsPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied MegaBits Per Second value to GigaBits Per Second
func (value MegaBitsPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied MegaBits Per Second value to TeraBits Per Second
func (value MegaBitsPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied MegaBits Per Second value to KiloBytes Per Second
func (value MegaBitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value * 125.0)
}
/// Converts the supplied MegaBits Per Second value to MegaBytes Per Second
func (value MegaBitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value / 8.0)
}
/// Converts the supplied MegaBits Per Second value to GigaBytes Per Second
func (value MegaBitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 8000.0)
}
/// Converts the supplied MegaBits Per Second value to TeraBytes Per Second
func (value MegaBitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 8e+6)
}
/// Converts the supplied MegaBits Per Second value to Kibibits Per Second
func (value MegaBitsPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 976.563)
}
/// Converts the supplied MegaBits Per Second value to Mebibits Per Second
func (value MegaBitsPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value / 1.04858)
}

/// MegaBytes Per Second conversion functions
type MegaBytesPerSecond float64

/// Converts the supplied MegaBytes Per Second value to Bits Per Second
func (value MegaBytesPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 8e+6)
}
/// Converts the supplied MegaBytes Per Second value to KiloBits Per Second
func (value MegaBytesPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 8000.0)
}
/// Converts the supplied MegaBytes Per Second value to MegaBits Per Second
func (value MegaBytesPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value * 8.0)
}
/// Converts the supplied MegaBytes Per Second value to GigaBits Per Second
func (value MegaBytesPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value / 125.0)
}
/// Converts the supplied MegaBytes Per Second value to TeraBits Per Second
func (value MegaBytesPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value / 125000.0)
}
/// Converts the supplied MegaBytes Per Second value to KiloBytes Per Second
func (value MegaBytesPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied MegaBytes Per Second value to GigaBytes Per Second
func (value MegaBytesPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied MegaBytes Per Second value to TeraBytes Per Second
func (value MegaBytesPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied MegaBytes Per Second value to Kibibits Per Second
func (value MegaBytesPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 7812.5)
}
/// Converts the supplied MegaBytes Per Second value to Mebibits Per Second
func (value MegaBytesPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value * 7.62939)
}

/// TeraBits Per Second conversion functions
type TeraBitsPerSecond float64

/// Converts the supplied TeraBits Per Second value to Bits Per Second
func (value TeraBitsPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 1e+12)
}
/// Converts the supplied TeraBits Per Second value to KiloBits Per Second
func (value TeraBitsPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 1e+9)
}
/// Converts the supplied TeraBits Per Second value to MegaBits Per Second
func (value TeraBitsPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied TeraBits Per Second value to GigaBits Per Second
func (value TeraBitsPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied TeraBits Per Second value to KiloBytes Per Second
func (value TeraBitsPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value * 1.25e+8)
}
/// Converts the supplied TeraBits Per Second value to MegaBytes Per Second
func (value TeraBitsPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value * 125000.0)
}
/// Converts the supplied TeraBits Per Second value to GigaBytes Per Second
func (value TeraBitsPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value * 125.0)
}
/// Converts the supplied TeraBits Per Second value to TeraBytes Per Second
func (value TeraBitsPerSecond) ToTeraBytesPerSecond() float64 { 
	return float64(value / 8.0)
}
/// Converts the supplied TeraBits Per Second value to Kibibits Per Second
func (value TeraBitsPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 976562500.0)
}
/// Converts the supplied TeraBits Per Second value to Mebibits Per Second
func (value TeraBitsPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value * 953674.0)
}

/// TeraBytes Per Second conversion functions
type TeraBytesPerSecond float64

/// Converts the supplied TeraBytes Per Second value to Bits Per Second
func (value TeraBytesPerSecond) ToBitsPerSecond() float64 { 
	return float64(value * 8e+12)
}
/// Converts the supplied TeraBytes Per Second value to KiloBits Per Second
func (value TeraBytesPerSecond) ToKiloBitsPerSecond() float64 { 
	return float64(value * 8e+9)
}
/// Converts the supplied TeraBytes Per Second value to MegaBits Per Second
func (value TeraBytesPerSecond) ToMegaBitsPerSecond() float64 { 
	return float64(value * 8e+6)
}
/// Converts the supplied TeraBytes Per Second value to GigaBits Per Second
func (value TeraBytesPerSecond) ToGigaBitsPerSecond() float64 { 
	return float64(value * 8000.0)
}
/// Converts the supplied TeraBytes Per Second value to TeraBits Per Second
func (value TeraBytesPerSecond) ToTeraBitsPerSecond() float64 { 
	return float64(value * 8.0)
}
/// Converts the supplied TeraBytes Per Second value to KiloBytes Per Second
func (value TeraBytesPerSecond) ToKiloBytesPerSecond() float64 { 
	return float64(value * 1e+9)
}
/// Converts the supplied TeraBytes Per Second value to MegaBytes Per Second
func (value TeraBytesPerSecond) ToMegaBytesPerSecond() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied TeraBytes Per Second value to GigaBytes Per Second
func (value TeraBytesPerSecond) ToGigaBytesPerSecond() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied TeraBytes Per Second value to Kibibits Per Second
func (value TeraBytesPerSecond) ToKibibitsPerSecond() float64 { 
	return float64(value * 7812500000.0)
}
/// Converts the supplied TeraBytes Per Second value to Mebibits Per Second
func (value TeraBytesPerSecond) ToMebibitsPerSecond() float64 { 
	return float64(value / 0.000000131072)
}
