// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package magnetomotiveforce

// Ampereturns (Ampere-turns) conversion functions
type Ampereturns float64

// ToGilberts converts the supplied Ampere-turns value to Gilberts
func (value Ampereturns) ToGilberts() float64 { 
	return float64(value / 0.7957747154595)
}

// Gilberts (Gilberts) conversion functions
type Gilberts float64

// ToAmpereturns converts the supplied Gilberts value to Ampere-turns
func (value Gilberts) ToAmpereturns() float64 { 
	return float64(value * 0.7957747154595)
}
