// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package pressure

import (
	"testing"
	"math"
	"github.com/google/go-cmp/cmp"
)

func withinTolerance() cmp.Option {
	return cmp.Comparer(func(x, y float64) bool {
		delta := math.Abs(x - y)
		mean := math.Abs(x + y) / 2.0
		return delta / mean < 0.01
	})
}
func TestConvertKnownAtmospheresToBars(t * testing.T) {
    if !cmp.Equal(Atmospheres.ToBars(6.0), 6.0795, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 6.0795, Atmospheres.ToBars(6.0));
    }
    if !cmp.Equal(Atmospheres.ToBars(1.2), 1.2159, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1.2159, Atmospheres.ToBars(1.2));
    }
    if !cmp.Equal(Atmospheres.ToBars(0.8), 0.8106, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.8106, Atmospheres.ToBars(0.8));
    }
}

func TestConvertKnownAtmospheresToPascals(t * testing.T) {
    if !cmp.Equal(Atmospheres.ToPascals(0.8), 81060.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 81060.0, Atmospheres.ToPascals(0.8));
    }
    if !cmp.Equal(Atmospheres.ToPascals(1.2), 121590.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 121590.0, Atmospheres.ToPascals(1.2));
    }
    if !cmp.Equal(Atmospheres.ToPascals(0.45), 45596.25, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 45596.25, Atmospheres.ToPascals(0.45));
    }
}

func TestConvertKnownAtmospheresToTorrs(t * testing.T) {
    if !cmp.Equal(Atmospheres.ToTorrs(0.45), 342.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 342.0, Atmospheres.ToTorrs(0.45));
    }
    if !cmp.Equal(Atmospheres.ToTorrs(1.2), 912.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 912.0, Atmospheres.ToTorrs(1.2));
    }
    if !cmp.Equal(Atmospheres.ToTorrs(6.0), 4560.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 4560.0, Atmospheres.ToTorrs(6.0));
    }
}

func TestConvertKnownAtmospheresToPsi(t * testing.T) {
    if !cmp.Equal(Atmospheres.ToPsi(6.0), 88.1757, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 88.1757, Atmospheres.ToPsi(6.0));
    }
    if !cmp.Equal(Atmospheres.ToPsi(0.4), 5.87838, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 5.87838, Atmospheres.ToPsi(0.4));
    }
    if !cmp.Equal(Atmospheres.ToPsi(1.2), 17.6351, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 17.6351, Atmospheres.ToPsi(1.2));
    }
}

func TestConvertKnownBarsToAtmospheres(t * testing.T) {
    if !cmp.Equal(Bars.ToAtmospheres(800.0), 789.539, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 789.539, Bars.ToAtmospheres(800.0));
    }
    if !cmp.Equal(Bars.ToAtmospheres(123.0), 121.392, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 121.392, Bars.ToAtmospheres(123.0));
    }
    if !cmp.Equal(Bars.ToAtmospheres(89.0), 87.8362, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 87.8362, Bars.ToAtmospheres(89.0));
    }
}

func TestConvertKnownBarsToPascals(t * testing.T) {
    if !cmp.Equal(Bars.ToPascals(0.89), 89000.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 89000.0, Bars.ToPascals(0.89));
    }
    if !cmp.Equal(Bars.ToPascals(0.01), 1000.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1000.0, Bars.ToPascals(0.01));
    }
    if !cmp.Equal(Bars.ToPascals(0.123), 12300.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 12300.0, Bars.ToPascals(0.123));
    }
}

func TestConvertKnownBarsToTorrs(t * testing.T) {
    if !cmp.Equal(Bars.ToTorrs(0.123), 92.257587, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 92.257587, Bars.ToTorrs(0.123));
    }
    if !cmp.Equal(Bars.ToTorrs(2.0), 1500.12, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1500.12, Bars.ToTorrs(2.0));
    }
    if !cmp.Equal(Bars.ToTorrs(8.9), 6675.55, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 6675.55, Bars.ToTorrs(8.9));
    }
}

func TestConvertKnownBarsToPsi(t * testing.T) {
    if !cmp.Equal(Bars.ToPsi(8.1), 117.481, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 117.481, Bars.ToPsi(8.1));
    }
    if !cmp.Equal(Bars.ToPsi(1001.0), 14518.29290, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 14518.29290, Bars.ToPsi(1001.0));
    }
    if !cmp.Equal(Bars.ToPsi(6.0), 87.0226, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 87.0226, Bars.ToPsi(6.0));
    }
}

func TestConvertKnownPascalsToAtmospheres(t * testing.T) {
    if !cmp.Equal(Pascals.ToAtmospheres(90000.0), 0.88823094, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.88823094, Pascals.ToAtmospheres(90000.0));
    }
    if !cmp.Equal(Pascals.ToAtmospheres(1234567.0), 12.18422897, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 12.18422897, Pascals.ToAtmospheres(1234567.0));
    }
    if !cmp.Equal(Pascals.ToAtmospheres(204060.0), 2.01391562, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 2.01391562, Pascals.ToAtmospheres(204060.0));
    }
}

func TestConvertKnownPascalsToBars(t * testing.T) {
    if !cmp.Equal(Pascals.ToBars(10000.0), 0.1, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.1, Pascals.ToBars(10000.0));
    }
    if !cmp.Equal(Pascals.ToBars(12345.0), 0.12345, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.12345, Pascals.ToBars(12345.0));
    }
    if !cmp.Equal(Pascals.ToBars(80000.0), 0.8, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.8, Pascals.ToBars(80000.0));
    }
}

func TestConvertKnownPascalsToTorrs(t * testing.T) {
    if !cmp.Equal(Pascals.ToTorrs(80000.0), 600.04935, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 600.04935, Pascals.ToTorrs(80000.0));
    }
    if !cmp.Equal(Pascals.ToTorrs(1234.0), 9.255761, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 9.255761, Pascals.ToTorrs(1234.0));
    }
    if !cmp.Equal(Pascals.ToTorrs(80.0), 0.600049, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.600049, Pascals.ToTorrs(80.0));
    }
}

func TestConvertKnownPascalsToPsi(t * testing.T) {
    if !cmp.Equal(Pascals.ToPsi(800.0), 0.11603, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.11603, Pascals.ToPsi(800.0));
    }
    if !cmp.Equal(Pascals.ToPsi(8670.0), 1.257477, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1.257477, Pascals.ToPsi(8670.0));
    }
    if !cmp.Equal(Pascals.ToPsi(1000.0), 0.145038, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.145038, Pascals.ToPsi(1000.0));
    }
}

func TestConvertKnownPsiToBars(t * testing.T) {
    if !cmp.Equal(Psi.ToBars(900.0), 62.0528, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 62.0528, Psi.ToBars(900.0));
    }
    if !cmp.Equal(Psi.ToBars(134.0), 9.23897, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 9.23897, Psi.ToBars(134.0));
    }
    if !cmp.Equal(Psi.ToBars(111.2), 7.6669701, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 7.6669701, Psi.ToBars(111.2));
    }
}

func TestConvertKnownPsiToPascals(t * testing.T) {
    if !cmp.Equal(Psi.ToPascals(0.9), 6205.28, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 6205.28, Psi.ToPascals(0.9));
    }
    if !cmp.Equal(Psi.ToPascals(0.03), 206.8427, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 206.8427, Psi.ToPascals(0.03));
    }
    if !cmp.Equal(Psi.ToPascals(2.0), 13789.5, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 13789.5, Psi.ToPascals(2.0));
    }
}

func TestConvertKnownPsiToAtmospheres(t * testing.T) {
    if !cmp.Equal(Psi.ToAtmospheres(2.0), 0.136092, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.136092, Psi.ToAtmospheres(2.0));
    }
    if !cmp.Equal(Psi.ToAtmospheres(109.0), 7.41701, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 7.41701, Psi.ToAtmospheres(109.0));
    }
    if !cmp.Equal(Psi.ToAtmospheres(8.0), 0.544368, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.544368, Psi.ToAtmospheres(8.0));
    }
}

func TestConvertKnownPsiToTorrs(t * testing.T) {
    if !cmp.Equal(Psi.ToTorrs(6.0), 310.29, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 310.29, Psi.ToTorrs(6.0));
    }
    if !cmp.Equal(Psi.ToTorrs(3.4), 175.831, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 175.831, Psi.ToTorrs(3.4));
    }
    if !cmp.Equal(Psi.ToTorrs(0.5), 25.8575, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 25.8575, Psi.ToTorrs(0.5));
    }
}

func TestConvertKnownTorrsToBars(t * testing.T) {
    if !cmp.Equal(Torrs.ToBars(100.0), 0.133322, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.133322, Torrs.ToBars(100.0));
    }
    if !cmp.Equal(Torrs.ToBars(9000.1), 11.9991465, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 11.9991465, Torrs.ToBars(9000.1));
    }
    if !cmp.Equal(Torrs.ToBars(1234.0), 1.645198, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1.645198, Torrs.ToBars(1234.0));
    }
}

func TestConvertKnownTorrsToPascals(t * testing.T) {
    if !cmp.Equal(Torrs.ToPascals(190.0), 25331.2499, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 25331.2499, Torrs.ToPascals(190.0));
    }
    if !cmp.Equal(Torrs.ToPascals(6.5), 866.595, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 866.595, Torrs.ToPascals(6.5));
    }
    if !cmp.Equal(Torrs.ToPascals(3.4), 453.296, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 453.296, Torrs.ToPascals(3.4));
    }
}

func TestConvertKnownTorrsToAtmospheres(t * testing.T) {
    if !cmp.Equal(Torrs.ToAtmospheres(5678.0), 7.471053, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 7.471053, Torrs.ToAtmospheres(5678.0));
    }
    if !cmp.Equal(Torrs.ToAtmospheres(100.0), 0.131579, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.131579, Torrs.ToAtmospheres(100.0));
    }
    if !cmp.Equal(Torrs.ToAtmospheres(4509.0), 5.932895, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 5.932895, Torrs.ToAtmospheres(4509.0));
    }
}

func TestConvertKnownTorrsToPsi(t * testing.T) {
    if !cmp.Equal(Torrs.ToPsi(4500.0), 87.01549, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 87.01549, Torrs.ToPsi(4500.0));
    }
    if !cmp.Equal(Torrs.ToPsi(1234.0), 23.86158, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 23.86158, Torrs.ToPsi(1234.0));
    }
    if !cmp.Equal(Torrs.ToPsi(900.0), 17.4031, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 17.4031, Torrs.ToPsi(900.0));
    }
}

