// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package luminousenergy

import (
	"testing"
	"math"
	"github.com/google/go-cmp/cmp"
)

func withinTolerance() cmp.Option {
	return cmp.Comparer(func(x, y float64) bool {
		delta := math.Abs(x - y)
		mean := math.Abs(x + y) / 2.0
		return delta / mean < 0.01
	})
}
func TestConvertKnownLumenHourToTalbot(t * testing.T) {
    if !cmp.Equal(LumenHour.ToTalbot(9.0), 32400.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 32400.0, LumenHour.ToTalbot(9.0));
    }
    if !cmp.Equal(LumenHour.ToTalbot(1.2), 4320.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 4320.0, LumenHour.ToTalbot(1.2));
    }
    if !cmp.Equal(LumenHour.ToTalbot(4.0), 14400.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 14400.0, LumenHour.ToTalbot(4.0));
    }
}

func TestConvertKnownLumenHourToLumenMinute(t * testing.T) {
    if !cmp.Equal(LumenHour.ToLumenMinute(1.2), 72.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 72.0, LumenHour.ToLumenMinute(1.2));
    }
    if !cmp.Equal(LumenHour.ToLumenMinute(0.8), 48.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 48.0, LumenHour.ToLumenMinute(0.8));
    }
    if !cmp.Equal(LumenHour.ToLumenMinute(109.00), 6540.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 6540.0, LumenHour.ToLumenMinute(109.00));
    }
}

func TestConvertKnownLumenHourToLumenSecond(t * testing.T) {
    if !cmp.Equal(LumenHour.ToLumenSecond(109.0), 392400.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 392400.0, LumenHour.ToLumenSecond(109.0));
    }
    if !cmp.Equal(LumenHour.ToLumenSecond(6.1), 21960.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 21960.0, LumenHour.ToLumenSecond(6.1));
    }
    if !cmp.Equal(LumenHour.ToLumenSecond(0.7), 2520.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 2520.0, LumenHour.ToLumenSecond(0.7));
    }
}

func TestConvertKnownLumenMinuteToTalbot(t * testing.T) {
    if !cmp.Equal(LumenMinute.ToTalbot(0.7), 42.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 42.0, LumenMinute.ToTalbot(0.7));
    }
    if !cmp.Equal(LumenMinute.ToTalbot(678.0), 40680.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 40680.0, LumenMinute.ToTalbot(678.0));
    }
    if !cmp.Equal(LumenMinute.ToTalbot(89.0), 5340.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 5340.0, LumenMinute.ToTalbot(89.0));
    }
}

func TestConvertKnownLumenMinuteToLumenHour(t * testing.T) {
    if !cmp.Equal(LumenMinute.ToLumenHour(89.0), 1.4833, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1.4833, LumenMinute.ToLumenHour(89.0));
    }
    if !cmp.Equal(LumenMinute.ToLumenHour(9.0), 0.15, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.15, LumenMinute.ToLumenHour(9.0));
    }
    if !cmp.Equal(LumenMinute.ToLumenHour(0.123), 0.00205, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.00205, LumenMinute.ToLumenHour(0.123));
    }
}

func TestConvertKnownLumenMinuteToLumenSecond(t * testing.T) {
    if !cmp.Equal(LumenMinute.ToLumenSecond(0.123), 7.38, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 7.38, LumenMinute.ToLumenSecond(0.123));
    }
    if !cmp.Equal(LumenMinute.ToLumenSecond(8000.0), 480000.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 480000.0, LumenMinute.ToLumenSecond(8000.0));
    }
    if !cmp.Equal(LumenMinute.ToLumenSecond(34.1), 2046.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 2046.0, LumenMinute.ToLumenSecond(34.1));
    }
}

func TestConvertKnownLumenSecondToTalbot(t * testing.T) {
    if !cmp.Equal(LumenSecond.ToTalbot(190.0), 190.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 190.0, LumenSecond.ToTalbot(190.0));
    }
    if !cmp.Equal(LumenSecond.ToTalbot(0.6), 0.6, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.6, LumenSecond.ToTalbot(0.6));
    }
    if !cmp.Equal(LumenSecond.ToTalbot(5000.0), 5000.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 5000.0, LumenSecond.ToTalbot(5000.0));
    }
}

func TestConvertKnownLumenSecondToLumenHour(t * testing.T) {
    if !cmp.Equal(LumenSecond.ToLumenHour(190.0), 0.052778, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.052778, LumenSecond.ToLumenHour(190.0));
    }
    if !cmp.Equal(LumenSecond.ToLumenHour(200600.0), 55.7222, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 55.7222, LumenSecond.ToLumenHour(200600.0));
    }
    if !cmp.Equal(LumenSecond.ToLumenHour(1234.0), 0.342778, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.342778, LumenSecond.ToLumenHour(1234.0));
    }
}

func TestConvertKnownLumenSecondToLumenMinute(t * testing.T) {
    if !cmp.Equal(LumenSecond.ToLumenMinute(10900.0), 181.6667, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 181.6667, LumenSecond.ToLumenMinute(10900.0));
    }
    if !cmp.Equal(LumenSecond.ToLumenMinute(50.3), 0.83833, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.83833, LumenSecond.ToLumenMinute(50.3));
    }
    if !cmp.Equal(LumenSecond.ToLumenMinute(276.0), 4.6, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 4.6, LumenSecond.ToLumenMinute(276.0));
    }
}

func TestConvertKnownTalbotToLumenSecond(t * testing.T) {
    if !cmp.Equal(Talbot.ToLumenSecond(100.0), 100.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 100.0, Talbot.ToLumenSecond(100.0));
    }
    if !cmp.Equal(Talbot.ToLumenSecond(0.9), 0.9, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.9, Talbot.ToLumenSecond(0.9));
    }
    if !cmp.Equal(Talbot.ToLumenSecond(23.1), 23.1, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 23.1, Talbot.ToLumenSecond(23.1));
    }
}

func TestConvertKnownTalbotToLumenHour(t * testing.T) {
    if !cmp.Equal(Talbot.ToLumenHour(800.0), 0.222, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 0.222, Talbot.ToLumenHour(800.0));
    }
    if !cmp.Equal(Talbot.ToLumenHour(6789.0), 1.885833, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1.885833, Talbot.ToLumenHour(6789.0));
    }
    if !cmp.Equal(Talbot.ToLumenHour(10900.0), 3.027778, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 3.027778, Talbot.ToLumenHour(10900.0));
    }
}

func TestConvertKnownTalbotToLumenMinute(t * testing.T) {
    if !cmp.Equal(Talbot.ToLumenMinute(900.0), 15.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 15.0, Talbot.ToLumenMinute(900.0));
    }
    if !cmp.Equal(Talbot.ToLumenMinute(78.9), 1.315, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 1.315, Talbot.ToLumenMinute(78.9));
    }
    if !cmp.Equal(Talbot.ToLumenMinute(1500.0), 25.0, withinTolerance()) {
        t.Fatalf("Expected %f, was %f", 25.0, Talbot.ToLumenMinute(1500.0));
    }
}

