// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package energy

/// Btu conversion functions
type Btu float64

/// Converts the supplied Btu value to Kilojoules
func (value Btu) ToKilojoules() float64 { 
	return float64(value * 1.0550559)
}
/// Converts the supplied Btu value to Kilocalories
func (value Btu) ToKilocalories() float64 { 
	return float64(value * 0.2521644007218)
}
/// Converts the supplied Btu value to Joules
func (value Btu) ToJoules() float64 { 
	return float64(value * 1055.06)
}
/// Converts the supplied Btu value to Calories
func (value Btu) ToCalories() float64 { 
	return float64(value * 252.1644007218)
}
/// Converts the supplied Btu value to US Therms
func (value Btu) ToUSTherms() float64 { 
	return float64(value / 99976.12448781215)
}
/// Converts the supplied Btu value to Watt Hours
func (value Btu) ToWattHours() float64 { 
	return float64(value * 0.293071)
}
/// Converts the supplied Btu value to Kilowatt Hours
func (value Btu) ToKilowattHours() float64 { 
	return float64(value / 3412.14)
}
/// Converts the supplied Btu value to Foot Pounds
func (value Btu) ToFootPounds() float64 { 
	return float64(value * 778.169)
}
/// Converts the supplied Btu value to Electronvolts
func (value Btu) ToElectronvolts() float64 { 
	return float64(value * 6585141385224143241216.00)
}

/// Calories conversion functions
type Calories float64

/// Converts the supplied Calories value to Kilojoules
func (value Calories) ToKilojoules() float64 { 
	return float64(value / 239.0057)
}
/// Converts the supplied Calories value to Kilocalories
func (value Calories) ToKilocalories() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Calories value to Joules
func (value Calories) ToJoules() float64 { 
	return float64(value * 4.184)
}
/// Converts the supplied Calories value to Btu
func (value Calories) ToBtu() float64 { 
	return float64(value / 252.1644007218)
}
/// Converts the supplied Calories value to US Therms
func (value Calories) ToUSTherms() float64 { 
	return float64(value / 25210420.0)
}
/// Converts the supplied Calories value to Watt Hours
func (value Calories) ToWattHours() float64 { 
	return float64(value * 0.00116222)
}
/// Converts the supplied Calories value to Kilowatt Hours
func (value Calories) ToKilowattHours() float64 { 
	return float64(value / 860421.0)
}
/// Converts the supplied Calories value to Foot Pounds
func (value Calories) ToFootPounds() float64 { 
	return float64(value * 3.08596)
}
/// Converts the supplied Calories value to Electronvolts
func (value Calories) ToElectronvolts() float64 { 
	return float64(value * 2.6131936951817e+19)
}

/// Electronvolts conversion functions
type Electronvolts float64

/// Converts the supplied Electronvolts value to Kilojoules
func (value Electronvolts) ToKilojoules() float64 { 
	return float64(value / 6241509744511500156928.00)
}
/// Converts the supplied Electronvolts value to Kilocalories
func (value Electronvolts) ToKilocalories() float64 { 
	return float64(value / 26131952998320305078272.00)
}
/// Converts the supplied Electronvolts value to Joules
func (value Electronvolts) ToJoules() float64 { 
	return float64(value / 6241509343300000000.0)
}
/// Converts the supplied Electronvolts value to Btu
func (value Electronvolts) ToBtu() float64 { 
	return float64(value / 6585141385224143241216.0)
}
/// Converts the supplied Electronvolts value to Calories
func (value Electronvolts) ToCalories() float64 { 
	return float64(value / 2.6131936951817e+19)
}
/// Converts the supplied Electronvolts value to US Therms
func (value Electronvolts) ToUSTherms() float64 { 
	return float64(value / 6.5835660010911e+26)
}
/// Converts the supplied Electronvolts value to Watt Hours
func (value Electronvolts) ToWattHours() float64 { 
	return float64(value / 2.2469422907138e+22)
}
/// Converts the supplied Electronvolts value to Kilowatt Hours
func (value Electronvolts) ToKilowattHours() float64 { 
	return float64(value / 2.246943e+25)
}
/// Converts the supplied Electronvolts value to Foot Pounds
func (value Electronvolts) ToFootPounds() float64 { 
	return float64(value / 8462350936293971968.00)
}

/// Foot Pounds conversion functions
type FootPounds float64

/// Converts the supplied Foot Pounds value to Kilojoules
func (value FootPounds) ToKilojoules() float64 { 
	return float64(value / 737.562)
}
/// Converts the supplied Foot Pounds value to Kilocalories
func (value FootPounds) ToKilocalories() float64 { 
	return float64(value / 3085.96)
}
/// Converts the supplied Foot Pounds value to Joules
func (value FootPounds) ToJoules() float64 { 
	return float64(value * 1.35582)
}
/// Converts the supplied Foot Pounds value to Btu
func (value FootPounds) ToBtu() float64 { 
	return float64(value / 778.169)
}
/// Converts the supplied Foot Pounds value to Calories
func (value FootPounds) ToCalories() float64 { 
	return float64(value / 3.08596)
}
/// Converts the supplied Foot Pounds value to US Therms
func (value FootPounds) ToUSTherms() float64 { 
	return float64(value / 77816937.099186)
}
/// Converts the supplied Foot Pounds value to Watt Hours
func (value FootPounds) ToWattHours() float64 { 
	return float64(value / 2655.22)
}
/// Converts the supplied Foot Pounds value to Kilowatt Hours
func (value FootPounds) ToKilowattHours() float64 { 
	return float64(value * 0.00000037662)
}
/// Converts the supplied Foot Pounds value to Electronvolts
func (value FootPounds) ToElectronvolts() float64 { 
	return float64(value * 8462350936293971968.00)
}

/// Joules conversion functions
type Joules float64

/// Converts the supplied Joules value to Kilojoules
func (value Joules) ToKilojoules() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Joules value to Kilocalories
func (value Joules) ToKilocalories() float64 { 
	return float64(value / 4184.0)
}
/// Converts the supplied Joules value to Btu
func (value Joules) ToBtu() float64 { 
	return float64(value / 1055.06)
}
/// Converts the supplied Joules value to Calories
func (value Joules) ToCalories() float64 { 
	return float64(value / 4.184)
}
/// Converts the supplied Joules value to US Therms
func (value Joules) ToUSTherms() float64 { 
	return float64(value / 105480400.0)
}
/// Converts the supplied Joules value to Watt Hours
func (value Joules) ToWattHours() float64 { 
	return float64(value / 3600.0)
}
/// Converts the supplied Joules value to Kilowatt Hours
func (value Joules) ToKilowattHours() float64 { 
	return float64(value / 3.6e+6)
}
/// Converts the supplied Joules value to Foot Pounds
func (value Joules) ToFootPounds() float64 { 
	return float64(value / 1.35582)
}
/// Converts the supplied Joules value to Electronvolts
func (value Joules) ToElectronvolts() float64 { 
	return float64(value * 6241509343300000000.0)
}

/// Kilocalories conversion functions
type Kilocalories float64

/// Converts the supplied Kilocalories value to Kilojoules
func (value Kilocalories) ToKilojoules() float64 { 
	return float64(value * 4.184)
}
/// Converts the supplied Kilocalories value to Joules
func (value Kilocalories) ToJoules() float64 { 
	return float64(value * 4184.0)
}
/// Converts the supplied Kilocalories value to Btu
func (value Kilocalories) ToBtu() float64 { 
	return float64(value / 0.2521644007218)
}
/// Converts the supplied Kilocalories value to Calories
func (value Kilocalories) ToCalories() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied Kilocalories value to US Therms
func (value Kilocalories) ToUSTherms() float64 { 
	return float64(value / 25210.44007218)
}
/// Converts the supplied Kilocalories value to Watt Hours
func (value Kilocalories) ToWattHours() float64 { 
	return float64(value * 1.16222)
}
/// Converts the supplied Kilocalories value to Kilowatt Hours
func (value Kilocalories) ToKilowattHours() float64 { 
	return float64(value / 860.421)
}
/// Converts the supplied Kilocalories value to Foot Pounds
func (value Kilocalories) ToFootPounds() float64 { 
	return float64(value * 3085.96)
}
/// Converts the supplied Kilocalories value to Electronvolts
func (value Kilocalories) ToElectronvolts() float64 { 
	return float64(value * 26131952998320305078272.00)
}

/// Kilojoules conversion functions
type Kilojoules float64

/// Converts the supplied Kilojoules value to Kilocalories
func (value Kilojoules) ToKilocalories() float64 { 
	return float64(value / 4.184)
}
/// Converts the supplied Kilojoules value to Joules
func (value Kilojoules) ToJoules() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied Kilojoules value to Btu
func (value Kilojoules) ToBtu() float64 { 
	return float64(value / 1.0550559)
}
/// Converts the supplied Kilojoules value to Calories
func (value Kilojoules) ToCalories() float64 { 
	return float64(value * 239.0057)
}
/// Converts the supplied Kilojoules value to US Therms
func (value Kilojoules) ToUSTherms() float64 { 
	return float64(value / 105480.04)
}
/// Converts the supplied Kilojoules value to Watt Hours
func (value Kilojoules) ToWattHours() float64 { 
	return float64(value / 3.6)
}
/// Converts the supplied Kilojoules value to Kilowatt Hours
func (value Kilojoules) ToKilowattHours() float64 { 
	return float64(value / 3600.0)
}
/// Converts the supplied Kilojoules value to Foot Pounds
func (value Kilojoules) ToFootPounds() float64 { 
	return float64(value * 737.562)
}
/// Converts the supplied Kilojoules value to Electronvolts
func (value Kilojoules) ToElectronvolts() float64 { 
	return float64(value * 6241509744511500156928.00)
}

/// Kilowatt Hours conversion functions
type KilowattHours float64

/// Converts the supplied Kilowatt Hours value to Kilojoules
func (value KilowattHours) ToKilojoules() float64 { 
	return float64(value * 3600.0)
}
/// Converts the supplied Kilowatt Hours value to Kilocalories
func (value KilowattHours) ToKilocalories() float64 { 
	return float64(value * 860.421)
}
/// Converts the supplied Kilowatt Hours value to Joules
func (value KilowattHours) ToJoules() float64 { 
	return float64(value * 3.6e+6)
}
/// Converts the supplied Kilowatt Hours value to Btu
func (value KilowattHours) ToBtu() float64 { 
	return float64(value * 3412.14)
}
/// Converts the supplied Kilowatt Hours value to Calories
func (value KilowattHours) ToCalories() float64 { 
	return float64(value * 860421.0)
}
/// Converts the supplied Kilowatt Hours value to US Therms
func (value KilowattHours) ToUSTherms() float64 { 
	return float64(value / 29.3001)
}
/// Converts the supplied Kilowatt Hours value to Watt Hours
func (value KilowattHours) ToWattHours() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied Kilowatt Hours value to Foot Pounds
func (value KilowattHours) ToFootPounds() float64 { 
	return float64(value / 0.00000037662)
}
/// Converts the supplied Kilowatt Hours value to Electronvolts
func (value KilowattHours) ToElectronvolts() float64 { 
	return float64(value * 2.246943e+25)
}

/// US Therms conversion functions
type USTherms float64

/// Converts the supplied US Therms value to Kilojoules
func (value USTherms) ToKilojoules() float64 { 
	return float64(value * 105480.04)
}
/// Converts the supplied US Therms value to Kilocalories
func (value USTherms) ToKilocalories() float64 { 
	return float64(value * 25210.44007218)
}
/// Converts the supplied US Therms value to Joules
func (value USTherms) ToJoules() float64 { 
	return float64(value * 105480400.0)
}
/// Converts the supplied US Therms value to Btu
func (value USTherms) ToBtu() float64 { 
	return float64(value * 99976.12448781215)
}
/// Converts the supplied US Therms value to Calories
func (value USTherms) ToCalories() float64 { 
	return float64(value * 25210420.0)
}
/// Converts the supplied US Therms value to Watt Hours
func (value USTherms) ToWattHours() float64 { 
	return float64(value * 29300.1)
}
/// Converts the supplied US Therms value to Kilowatt Hours
func (value USTherms) ToKilowattHours() float64 { 
	return float64(value * 29.3001)
}
/// Converts the supplied US Therms value to Foot Pounds
func (value USTherms) ToFootPounds() float64 { 
	return float64(value * 77816937.099186)
}
/// Converts the supplied US Therms value to Electronvolts
func (value USTherms) ToElectronvolts() float64 { 
	return float64(value * 6.5835660010911e+26)
}

/// Watt Hours conversion functions
type WattHours float64

/// Converts the supplied Watt Hours value to Kilojoules
func (value WattHours) ToKilojoules() float64 { 
	return float64(value * 3.6)
}
/// Converts the supplied Watt Hours value to Kilocalories
func (value WattHours) ToKilocalories() float64 { 
	return float64(value / 1.16222)
}
/// Converts the supplied Watt Hours value to Joules
func (value WattHours) ToJoules() float64 { 
	return float64(value * 3600.0)
}
/// Converts the supplied Watt Hours value to Btu
func (value WattHours) ToBtu() float64 { 
	return float64(value / 0.293071)
}
/// Converts the supplied Watt Hours value to Calories
func (value WattHours) ToCalories() float64 { 
	return float64(value / 0.00116222)
}
/// Converts the supplied Watt Hours value to US Therms
func (value WattHours) ToUSTherms() float64 { 
	return float64(value / 29300.1)
}
/// Converts the supplied Watt Hours value to Kilowatt Hours
func (value WattHours) ToKilowattHours() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Watt Hours value to Foot Pounds
func (value WattHours) ToFootPounds() float64 { 
	return float64(value * 2655.22)
}
/// Converts the supplied Watt Hours value to Electronvolts
func (value WattHours) ToElectronvolts() float64 { 
	return float64(value * 2.2469422907138e+22)
}
