// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package time

/// Centuries conversion functions
type Centuries float64

/// Converts the supplied Centuries value to Nanoseconds
func (value Centuries) ToNanoseconds() float64 { 
	return float64(value * 3.154e+18)
}
/// Converts the supplied Centuries value to Microseconds
func (value Centuries) ToMicroseconds() float64 { 
	return float64(value * 3.154e+15)
}
/// Converts the supplied Centuries value to Milliseconds
func (value Centuries) ToMilliseconds() float64 { 
	return float64(value * 3.154e+12)
}
/// Converts the supplied Centuries value to Seconds
func (value Centuries) ToSeconds() float64 { 
	return float64(value * 3.154e+9)
}
/// Converts the supplied Centuries value to Minutes
func (value Centuries) ToMinutes() float64 { 
	return float64(value * 5.256e+7)
}
/// Converts the supplied Centuries value to Hours
func (value Centuries) ToHours() float64 { 
	return float64(value * 876000.0)
}
/// Converts the supplied Centuries value to Days
func (value Centuries) ToDays() float64 { 
	return float64(value * 36500.0)
}
/// Converts the supplied Centuries value to Weeks
func (value Centuries) ToWeeks() float64 { 
	return float64(value * 5214.29)
}
/// Converts the supplied Centuries value to Months
func (value Centuries) ToMonths() float64 { 
	return float64(value * 1200.0)
}
/// Converts the supplied Centuries value to Years
func (value Centuries) ToYears() float64 { 
	return float64(value * 100.0)
}
/// Converts the supplied Centuries value to Decades
func (value Centuries) ToDecades() float64 { 
	return float64(value * 10.0)
}

/// Days conversion functions
type Days float64

/// Converts the supplied Days value to Nanoseconds
func (value Days) ToNanoseconds() float64 { 
	return float64(value * 8.64e+13)
}
/// Converts the supplied Days value to Microseconds
func (value Days) ToMicroseconds() float64 { 
	return float64(value * 8.64e+10)
}
/// Converts the supplied Days value to Milliseconds
func (value Days) ToMilliseconds() float64 { 
	return float64(value * 8.64e+7)
}
/// Converts the supplied Days value to Seconds
func (value Days) ToSeconds() float64 { 
	return float64(value * 86400.0)
}
/// Converts the supplied Days value to Minutes
func (value Days) ToMinutes() float64 { 
	return float64(value * 1440.0)
}
/// Converts the supplied Days value to Hours
func (value Days) ToHours() float64 { 
	return float64(value * 24.0)
}
/// Converts the supplied Days value to Weeks
func (value Days) ToWeeks() float64 { 
	return float64(value / 7.0)
}
/// Converts the supplied Days value to Months
func (value Days) ToMonths() float64 { 
	return float64(value / 30.4167)
}
/// Converts the supplied Days value to Years
func (value Days) ToYears() float64 { 
	return float64(value / 365.0)
}
/// Converts the supplied Days value to Decades
func (value Days) ToDecades() float64 { 
	return float64(value / 3650.0)
}
/// Converts the supplied Days value to Centuries
func (value Days) ToCenturies() float64 { 
	return float64(value / 36500.0)
}

/// Decades conversion functions
type Decades float64

/// Converts the supplied Decades value to Nanoseconds
func (value Decades) ToNanoseconds() float64 { 
	return float64(value * 3.154e+17)
}
/// Converts the supplied Decades value to Microseconds
func (value Decades) ToMicroseconds() float64 { 
	return float64(value * 3.154e+14)
}
/// Converts the supplied Decades value to Milliseconds
func (value Decades) ToMilliseconds() float64 { 
	return float64(value * 3.154e+11)
}
/// Converts the supplied Decades value to Seconds
func (value Decades) ToSeconds() float64 { 
	return float64(value * 3.154e+8)
}
/// Converts the supplied Decades value to Minutes
func (value Decades) ToMinutes() float64 { 
	return float64(value * 5.256e+6)
}
/// Converts the supplied Decades value to Hours
func (value Decades) ToHours() float64 { 
	return float64(value * 87600.0)
}
/// Converts the supplied Decades value to Days
func (value Decades) ToDays() float64 { 
	return float64(value * 3650.0)
}
/// Converts the supplied Decades value to Weeks
func (value Decades) ToWeeks() float64 { 
	return float64(value * 521.429)
}
/// Converts the supplied Decades value to Months
func (value Decades) ToMonths() float64 { 
	return float64(value * 120.0)
}
/// Converts the supplied Decades value to Years
func (value Decades) ToYears() float64 { 
	return float64(value * 10.0)
}
/// Converts the supplied Decades value to Centuries
func (value Decades) ToCenturies() float64 { 
	return float64(value / 10.0)
}

/// Hours conversion functions
type Hours float64

/// Converts the supplied Hours value to Nanoseconds
func (value Hours) ToNanoseconds() float64 { 
	return float64(value * 3.6e+12)
}
/// Converts the supplied Hours value to Microseconds
func (value Hours) ToMicroseconds() float64 { 
	return float64(value * 3.6e+9)
}
/// Converts the supplied Hours value to Milliseconds
func (value Hours) ToMilliseconds() float64 { 
	return float64(value * 3.6e+6)
}
/// Converts the supplied Hours value to Seconds
func (value Hours) ToSeconds() float64 { 
	return float64(value * 3600.0)
}
/// Converts the supplied Hours value to Minutes
func (value Hours) ToMinutes() float64 { 
	return float64(value * 60.0)
}
/// Converts the supplied Hours value to Days
func (value Hours) ToDays() float64 { 
	return float64(value / 24.0)
}
/// Converts the supplied Hours value to Weeks
func (value Hours) ToWeeks() float64 { 
	return float64(value / 168.0)
}
/// Converts the supplied Hours value to Months
func (value Hours) ToMonths() float64 { 
	return float64(value / 730.001)
}
/// Converts the supplied Hours value to Years
func (value Hours) ToYears() float64 { 
	return float64(value / 8760.0)
}
/// Converts the supplied Hours value to Decades
func (value Hours) ToDecades() float64 { 
	return float64(value / 87600.0)
}
/// Converts the supplied Hours value to Centuries
func (value Hours) ToCenturies() float64 { 
	return float64(value / 876000.0)
}

/// Microseconds conversion functions
type Microseconds float64

/// Converts the supplied Microseconds value to Nanoseconds
func (value Microseconds) ToNanoseconds() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied Microseconds value to Milliseconds
func (value Microseconds) ToMilliseconds() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Microseconds value to Seconds
func (value Microseconds) ToSeconds() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied Microseconds value to Minutes
func (value Microseconds) ToMinutes() float64 { 
	return float64(value / 6e+7)
}
/// Converts the supplied Microseconds value to Hours
func (value Microseconds) ToHours() float64 { 
	return float64(value / 3.6e+9)
}
/// Converts the supplied Microseconds value to Days
func (value Microseconds) ToDays() float64 { 
	return float64(value / 8.64e+10)
}
/// Converts the supplied Microseconds value to Weeks
func (value Microseconds) ToWeeks() float64 { 
	return float64(value / 6.048e+11)
}
/// Converts the supplied Microseconds value to Months
func (value Microseconds) ToMonths() float64 { 
	return float64(value / 2629746000000.0)
}
/// Converts the supplied Microseconds value to Years
func (value Microseconds) ToYears() float64 { 
	return float64(value / 3.154e+13)
}
/// Converts the supplied Microseconds value to Decades
func (value Microseconds) ToDecades() float64 { 
	return float64(value / 3.154e+14)
}
/// Converts the supplied Microseconds value to Centuries
func (value Microseconds) ToCenturies() float64 { 
	return float64(value / 3.154e+15)
}

/// Milliseconds conversion functions
type Milliseconds float64

/// Converts the supplied Milliseconds value to Nanoseconds
func (value Milliseconds) ToNanoseconds() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied Milliseconds value to Microseconds
func (value Milliseconds) ToMicroseconds() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied Milliseconds value to Seconds
func (value Milliseconds) ToSeconds() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Milliseconds value to Minutes
func (value Milliseconds) ToMinutes() float64 { 
	return float64(value / 60000.0)
}
/// Converts the supplied Milliseconds value to Hours
func (value Milliseconds) ToHours() float64 { 
	return float64(value / 3.6e+6)
}
/// Converts the supplied Milliseconds value to Days
func (value Milliseconds) ToDays() float64 { 
	return float64(value / 8.64e+7)
}
/// Converts the supplied Milliseconds value to Weeks
func (value Milliseconds) ToWeeks() float64 { 
	return float64(value / 6.048e+8)
}
/// Converts the supplied Milliseconds value to Months
func (value Milliseconds) ToMonths() float64 { 
	return float64(value / 2629746000.0)
}
/// Converts the supplied Milliseconds value to Years
func (value Milliseconds) ToYears() float64 { 
	return float64(value / 31556952000.0)
}
/// Converts the supplied Milliseconds value to Decades
func (value Milliseconds) ToDecades() float64 { 
	return float64(value / 3.154e+11)
}
/// Converts the supplied Milliseconds value to Centuries
func (value Milliseconds) ToCenturies() float64 { 
	return float64(value / 3.154e+12)
}

/// Minutes conversion functions
type Minutes float64

/// Converts the supplied Minutes value to Nanoseconds
func (value Minutes) ToNanoseconds() float64 { 
	return float64(value * 6e+10)
}
/// Converts the supplied Minutes value to Microseconds
func (value Minutes) ToMicroseconds() float64 { 
	return float64(value * 6e+7)
}
/// Converts the supplied Minutes value to Milliseconds
func (value Minutes) ToMilliseconds() float64 { 
	return float64(value * 60000.0)
}
/// Converts the supplied Minutes value to Seconds
func (value Minutes) ToSeconds() float64 { 
	return float64(value * 60.0)
}
/// Converts the supplied Minutes value to Hours
func (value Minutes) ToHours() float64 { 
	return float64(value / 60.0)
}
/// Converts the supplied Minutes value to Days
func (value Minutes) ToDays() float64 { 
	return float64(value / 1440.0)
}
/// Converts the supplied Minutes value to Weeks
func (value Minutes) ToWeeks() float64 { 
	return float64(value / 10080.0)
}
/// Converts the supplied Minutes value to Months
func (value Minutes) ToMonths() float64 { 
	return float64(value / 43800.0)
}
/// Converts the supplied Minutes value to Years
func (value Minutes) ToYears() float64 { 
	return float64(value / 525600.0)
}
/// Converts the supplied Minutes value to Decades
func (value Minutes) ToDecades() float64 { 
	return float64(value / 5.256e+6)
}
/// Converts the supplied Minutes value to Centuries
func (value Minutes) ToCenturies() float64 { 
	return float64(value / 5.256e+7)
}

/// Months conversion functions
type Months float64

/// Converts the supplied Months value to Nanoseconds
func (value Months) ToNanoseconds() float64 { 
	return float64(value * 2629746000000000.0)
}
/// Converts the supplied Months value to Microseconds
func (value Months) ToMicroseconds() float64 { 
	return float64(value * 2629746000000.0)
}
/// Converts the supplied Months value to Milliseconds
func (value Months) ToMilliseconds() float64 { 
	return float64(value * 2629746000.0)
}
/// Converts the supplied Months value to Seconds
func (value Months) ToSeconds() float64 { 
	return float64(value * 2.628e+6)
}
/// Converts the supplied Months value to Minutes
func (value Months) ToMinutes() float64 { 
	return float64(value * 43800.0)
}
/// Converts the supplied Months value to Hours
func (value Months) ToHours() float64 { 
	return float64(value * 730.001)
}
/// Converts the supplied Months value to Days
func (value Months) ToDays() float64 { 
	return float64(value * 30.4167)
}
/// Converts the supplied Months value to Weeks
func (value Months) ToWeeks() float64 { 
	return float64(value * 4.34524)
}
/// Converts the supplied Months value to Years
func (value Months) ToYears() float64 { 
	return float64(value / 12.0)
}
/// Converts the supplied Months value to Decades
func (value Months) ToDecades() float64 { 
	return float64(value / 120.0)
}
/// Converts the supplied Months value to Centuries
func (value Months) ToCenturies() float64 { 
	return float64(value / 1200.0)
}

/// Nanoseconds conversion functions
type Nanoseconds float64

/// Converts the supplied Nanoseconds value to Microseconds
func (value Nanoseconds) ToMicroseconds() float64 { 
	return float64(value / 1000.0)
}
/// Converts the supplied Nanoseconds value to Milliseconds
func (value Nanoseconds) ToMilliseconds() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied Nanoseconds value to Seconds
func (value Nanoseconds) ToSeconds() float64 { 
	return float64(value / 1e+9)
}
/// Converts the supplied Nanoseconds value to Minutes
func (value Nanoseconds) ToMinutes() float64 { 
	return float64(value / 6e+10)
}
/// Converts the supplied Nanoseconds value to Hours
func (value Nanoseconds) ToHours() float64 { 
	return float64(value / 3.6e+12)
}
/// Converts the supplied Nanoseconds value to Days
func (value Nanoseconds) ToDays() float64 { 
	return float64(value / 8.64e+13)
}
/// Converts the supplied Nanoseconds value to Weeks
func (value Nanoseconds) ToWeeks() float64 { 
	return float64(value / 6.048e+14)
}
/// Converts the supplied Nanoseconds value to Months
func (value Nanoseconds) ToMonths() float64 { 
	return float64(value / 2629746000000000.0)
}
/// Converts the supplied Nanoseconds value to Years
func (value Nanoseconds) ToYears() float64 { 
	return float64(value / 3.154e+16)
}
/// Converts the supplied Nanoseconds value to Decades
func (value Nanoseconds) ToDecades() float64 { 
	return float64(value / 3.154e+17)
}
/// Converts the supplied Nanoseconds value to Centuries
func (value Nanoseconds) ToCenturies() float64 { 
	return float64(value / 3.154e+18)
}

/// Seconds conversion functions
type Seconds float64

/// Converts the supplied Seconds value to Nanoseconds
func (value Seconds) ToNanoseconds() float64 { 
	return float64(value * 1e+9)
}
/// Converts the supplied Seconds value to Microseconds
func (value Seconds) ToMicroseconds() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied Seconds value to Milliseconds
func (value Seconds) ToMilliseconds() float64 { 
	return float64(value * 1000.0)
}
/// Converts the supplied Seconds value to Minutes
func (value Seconds) ToMinutes() float64 { 
	return float64(value / 60.0)
}
/// Converts the supplied Seconds value to Hours
func (value Seconds) ToHours() float64 { 
	return float64(value / 3600.0)
}
/// Converts the supplied Seconds value to Days
func (value Seconds) ToDays() float64 { 
	return float64(value / 86400.0)
}
/// Converts the supplied Seconds value to Weeks
func (value Seconds) ToWeeks() float64 { 
	return float64(value / 604800.0)
}
/// Converts the supplied Seconds value to Months
func (value Seconds) ToMonths() float64 { 
	return float64(value / 2.628e+6)
}
/// Converts the supplied Seconds value to Years
func (value Seconds) ToYears() float64 { 
	return float64(value / 3.1536e+7)
}
/// Converts the supplied Seconds value to Decades
func (value Seconds) ToDecades() float64 { 
	return float64(value / 3.154e+8)
}
/// Converts the supplied Seconds value to Centuries
func (value Seconds) ToCenturies() float64 { 
	return float64(value / 3.154e+9)
}

/// Weeks conversion functions
type Weeks float64

/// Converts the supplied Weeks value to Nanoseconds
func (value Weeks) ToNanoseconds() float64 { 
	return float64(value * 6.048e+14)
}
/// Converts the supplied Weeks value to Microseconds
func (value Weeks) ToMicroseconds() float64 { 
	return float64(value * 6.048e+11)
}
/// Converts the supplied Weeks value to Milliseconds
func (value Weeks) ToMilliseconds() float64 { 
	return float64(value * 6.048e+8)
}
/// Converts the supplied Weeks value to Seconds
func (value Weeks) ToSeconds() float64 { 
	return float64(value * 604800.0)
}
/// Converts the supplied Weeks value to Minutes
func (value Weeks) ToMinutes() float64 { 
	return float64(value * 10080.0)
}
/// Converts the supplied Weeks value to Hours
func (value Weeks) ToHours() float64 { 
	return float64(value * 168.0)
}
/// Converts the supplied Weeks value to Days
func (value Weeks) ToDays() float64 { 
	return float64(value * 7.0)
}
/// Converts the supplied Weeks value to Months
func (value Weeks) ToMonths() float64 { 
	return float64(value / 4.34524)
}
/// Converts the supplied Weeks value to Years
func (value Weeks) ToYears() float64 { 
	return float64(value / 52.143)
}
/// Converts the supplied Weeks value to Decades
func (value Weeks) ToDecades() float64 { 
	return float64(value / 521.429)
}
/// Converts the supplied Weeks value to Centuries
func (value Weeks) ToCenturies() float64 { 
	return float64(value / 5214.29)
}

/// Years conversion functions
type Years float64

/// Converts the supplied Years value to Nanoseconds
func (value Years) ToNanoseconds() float64 { 
	return float64(value * 3.154e+16)
}
/// Converts the supplied Years value to Microseconds
func (value Years) ToMicroseconds() float64 { 
	return float64(value * 3.154e+13)
}
/// Converts the supplied Years value to Milliseconds
func (value Years) ToMilliseconds() float64 { 
	return float64(value * 31556952000.0)
}
/// Converts the supplied Years value to Seconds
func (value Years) ToSeconds() float64 { 
	return float64(value * 3.1536e+7)
}
/// Converts the supplied Years value to Minutes
func (value Years) ToMinutes() float64 { 
	return float64(value * 525600.0)
}
/// Converts the supplied Years value to Hours
func (value Years) ToHours() float64 { 
	return float64(value * 8760.0)
}
/// Converts the supplied Years value to Days
func (value Years) ToDays() float64 { 
	return float64(value * 365.0)
}
/// Converts the supplied Years value to Weeks
func (value Years) ToWeeks() float64 { 
	return float64(value * 52.143)
}
/// Converts the supplied Years value to Months
func (value Years) ToMonths() float64 { 
	return float64(value * 12.0)
}
/// Converts the supplied Years value to Decades
func (value Years) ToDecades() float64 { 
	return float64(value / 10.0)
}
/// Converts the supplied Years value to Centuries
func (value Years) ToCenturies() float64 { 
	return float64(value / 100.0)
}
