// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package magnetomotive_force

/// Ampere-turns conversion functions
type Ampereturns float64

/// Converts the supplied Ampere-turns value to Gilberts
func (value Ampereturns) ToGilberts() float64 { 
	return float64(value / 0.7957747154595)
}

/// Gilberts conversion functions
type Gilberts float64

/// Converts the supplied Gilberts value to Ampere-turns
func (value Gilberts) ToAmpereturns() float64 { 
	return float64(value * 0.7957747154595)
}
