// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package area

/// Acres conversion functions
type Acres float64

/// Converts the supplied Acres value to Square Kilometres
func (value Acres) ToSquareKilometres() float64 { 
	return float64(value / 247.105)
}
/// Converts the supplied Acres value to Square Metres
func (value Acres) ToSquareMetres() float64 { 
	return float64(value * 4046.86)
}
/// Converts the supplied Acres value to Square Miles
func (value Acres) ToSquareMiles() float64 { 
	return float64(value / 640.0)
}
/// Converts the supplied Acres value to Square Yards
func (value Acres) ToSquareYards() float64 { 
	return float64(value * 4840.0)
}
/// Converts the supplied Acres value to Square Feet
func (value Acres) ToSquareFeet() float64 { 
	return float64(value * 43560.0)
}
/// Converts the supplied Acres value to Square Inches
func (value Acres) ToSquareInches() float64 { 
	return float64(value * 6272640.0)
}
/// Converts the supplied Acres value to Hectares
func (value Acres) ToHectares() float64 { 
	return float64(value / 2.4710538146717)
}

/// Hectares conversion functions
type Hectares float64

/// Converts the supplied Hectares value to Square Kilometres
func (value Hectares) ToSquareKilometres() float64 { 
	return float64(value / 100.0)
}
/// Converts the supplied Hectares value to Square Metres
func (value Hectares) ToSquareMetres() float64 { 
	return float64(value * 10000.0)
}
/// Converts the supplied Hectares value to Square Miles
func (value Hectares) ToSquareMiles() float64 { 
	return float64(value / 258.99881103)
}
/// Converts the supplied Hectares value to Square Yards
func (value Hectares) ToSquareYards() float64 { 
	return float64(value * 11959.900463011)
}
/// Converts the supplied Hectares value to Square Feet
func (value Hectares) ToSquareFeet() float64 { 
	return float64(value * 107639.0)
}
/// Converts the supplied Hectares value to Square Inches
func (value Hectares) ToSquareInches() float64 { 
	return float64(value * 15500031.0)
}
/// Converts the supplied Hectares value to Acres
func (value Hectares) ToAcres() float64 { 
	return float64(value * 2.4710538146717)
}

/// Square Feet conversion functions
type SquareFeet float64

/// Converts the supplied Square Feet value to Square Kilometres
func (value SquareFeet) ToSquareKilometres() float64 { 
	return float64(value / 10763910.41671)
}
/// Converts the supplied Square Feet value to Square Metres
func (value SquareFeet) ToSquareMetres() float64 { 
	return float64(value / 10.76391042)
}
/// Converts the supplied Square Feet value to Square Miles
func (value SquareFeet) ToSquareMiles() float64 { 
	return float64(value / 27878400.0)
}
/// Converts the supplied Square Feet value to Square Yards
func (value SquareFeet) ToSquareYards() float64 { 
	return float64(value / 9.0)
}
/// Converts the supplied Square Feet value to Square Inches
func (value SquareFeet) ToSquareInches() float64 { 
	return float64(value * 144.0)
}
/// Converts the supplied Square Feet value to Hectares
func (value SquareFeet) ToHectares() float64 { 
	return float64(value / 107639.0)
}
/// Converts the supplied Square Feet value to Acres
func (value SquareFeet) ToAcres() float64 { 
	return float64(value / 43560.0)
}

/// Square Inches conversion functions
type SquareInches float64

/// Converts the supplied Square Inches value to Square Kilometres
func (value SquareInches) ToSquareKilometres() float64 { 
	return float64(value / 1550003100.00)
}
/// Converts the supplied Square Inches value to Square Metres
func (value SquareInches) ToSquareMetres() float64 { 
	return float64(value / 1550.0)
}
/// Converts the supplied Square Inches value to Square Miles
func (value SquareInches) ToSquareMiles() float64 { 
	return float64(value / 4014489600.0)
}
/// Converts the supplied Square Inches value to Square Yards
func (value SquareInches) ToSquareYards() float64 { 
	return float64(value / 1296.0)
}
/// Converts the supplied Square Inches value to Square Feet
func (value SquareInches) ToSquareFeet() float64 { 
	return float64(value / 144.0)
}
/// Converts the supplied Square Inches value to Hectares
func (value SquareInches) ToHectares() float64 { 
	return float64(value / 15500031.0)
}
/// Converts the supplied Square Inches value to Acres
func (value SquareInches) ToAcres() float64 { 
	return float64(value / 6272640.0)
}

/// Square Kilometres conversion functions
type SquareKilometres float64

/// Converts the supplied Square Kilometres value to Square Metres
func (value SquareKilometres) ToSquareMetres() float64 { 
	return float64(value * 1e+6)
}
/// Converts the supplied Square Kilometres value to Square Miles
func (value SquareKilometres) ToSquareMiles() float64 { 
	return float64(value / 2.58999)
}
/// Converts the supplied Square Kilometres value to Square Yards
func (value SquareKilometres) ToSquareYards() float64 { 
	return float64(value * 1195990.05)
}
/// Converts the supplied Square Kilometres value to Square Feet
func (value SquareKilometres) ToSquareFeet() float64 { 
	return float64(value * 10763910.41671)
}
/// Converts the supplied Square Kilometres value to Square Inches
func (value SquareKilometres) ToSquareInches() float64 { 
	return float64(value * 1550003100.00)
}
/// Converts the supplied Square Kilometres value to Hectares
func (value SquareKilometres) ToHectares() float64 { 
	return float64(value * 100.0)
}
/// Converts the supplied Square Kilometres value to Acres
func (value SquareKilometres) ToAcres() float64 { 
	return float64(value * 247.105)
}

/// Square Metres conversion functions
type SquareMetres float64

/// Converts the supplied Square Metres value to Square Kilometres
func (value SquareMetres) ToSquareKilometres() float64 { 
	return float64(value / 1e+6)
}
/// Converts the supplied Square Metres value to Square Miles
func (value SquareMetres) ToSquareMiles() float64 { 
	return float64(value / 2589988.10)
}
/// Converts the supplied Square Metres value to Square Yards
func (value SquareMetres) ToSquareYards() float64 { 
	return float64(value * 1.1959900463)
}
/// Converts the supplied Square Metres value to Square Feet
func (value SquareMetres) ToSquareFeet() float64 { 
	return float64(value * 10.76391042)
}
/// Converts the supplied Square Metres value to Square Inches
func (value SquareMetres) ToSquareInches() float64 { 
	return float64(value * 1550.0)
}
/// Converts the supplied Square Metres value to Hectares
func (value SquareMetres) ToHectares() float64 { 
	return float64(value / 10000.0)
}
/// Converts the supplied Square Metres value to Acres
func (value SquareMetres) ToAcres() float64 { 
	return float64(value / 4046.86)
}

/// Square Miles conversion functions
type SquareMiles float64

/// Converts the supplied Square Miles value to Square Kilometres
func (value SquareMiles) ToSquareKilometres() float64 { 
	return float64(value * 2.58999)
}
/// Converts the supplied Square Miles value to Square Metres
func (value SquareMiles) ToSquareMetres() float64 { 
	return float64(value * 2589988.10)
}
/// Converts the supplied Square Miles value to Square Yards
func (value SquareMiles) ToSquareYards() float64 { 
	return float64(value * 3097600.0)
}
/// Converts the supplied Square Miles value to Square Feet
func (value SquareMiles) ToSquareFeet() float64 { 
	return float64(value * 27878400.0)
}
/// Converts the supplied Square Miles value to Square Inches
func (value SquareMiles) ToSquareInches() float64 { 
	return float64(value * 4014489600.0)
}
/// Converts the supplied Square Miles value to Hectares
func (value SquareMiles) ToHectares() float64 { 
	return float64(value * 258.99881103)
}
/// Converts the supplied Square Miles value to Acres
func (value SquareMiles) ToAcres() float64 { 
	return float64(value * 640.0)
}

/// Square Yards conversion functions
type SquareYards float64

/// Converts the supplied Square Yards value to Square Kilometres
func (value SquareYards) ToSquareKilometres() float64 { 
	return float64(value / 1195990.05)
}
/// Converts the supplied Square Yards value to Square Metres
func (value SquareYards) ToSquareMetres() float64 { 
	return float64(value / 1.1959900463)
}
/// Converts the supplied Square Yards value to Square Miles
func (value SquareYards) ToSquareMiles() float64 { 
	return float64(value / 3097600.0)
}
/// Converts the supplied Square Yards value to Square Feet
func (value SquareYards) ToSquareFeet() float64 { 
	return float64(value * 9.0)
}
/// Converts the supplied Square Yards value to Square Inches
func (value SquareYards) ToSquareInches() float64 { 
	return float64(value * 1296.0)
}
/// Converts the supplied Square Yards value to Hectares
func (value SquareYards) ToHectares() float64 { 
	return float64(value / 11959.900463011)
}
/// Converts the supplied Square Yards value to Acres
func (value SquareYards) ToAcres() float64 { 
	return float64(value / 4840.0)
}
