// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

package speed

/// Feet Per Second conversion functions
type FeetPerSecond float64

/// Converts the supplied Feet Per Second value to Miles Per Hour
func (value FeetPerSecond) ToMilesPerHour() float64 { 
	return float64(value / 1.46667)
}
/// Converts the supplied Feet Per Second value to Kilometres Per Hour
func (value FeetPerSecond) ToKilometresPerHour() float64 { 
	return float64(value * 1.09728)
}
/// Converts the supplied Feet Per Second value to Metres Per Second
func (value FeetPerSecond) ToMetresPerSecond() float64 { 
	return float64(value / 3.28084)
}
/// Converts the supplied Feet Per Second value to Knots
func (value FeetPerSecond) ToKnots() float64 { 
	return float64(value / 1.68781)
}

/// Kilometres Per Hour conversion functions
type KilometresPerHour float64

/// Converts the supplied Kilometres Per Hour value to Miles Per Hour
func (value KilometresPerHour) ToMilesPerHour() float64 { 
	return float64(value / 1.60934)
}
/// Converts the supplied Kilometres Per Hour value to Feet Per Second
func (value KilometresPerHour) ToFeetPerSecond() float64 { 
	return float64(value / 1.09728)
}
/// Converts the supplied Kilometres Per Hour value to Metres Per Second
func (value KilometresPerHour) ToMetresPerSecond() float64 { 
	return float64(value / 3.6)
}
/// Converts the supplied Kilometres Per Hour value to Knots
func (value KilometresPerHour) ToKnots() float64 { 
	return float64(value / 1.852)
}

/// Knots conversion functions
type Knots float64

/// Converts the supplied Knots value to Miles Per Hour
func (value Knots) ToMilesPerHour() float64 { 
	return float64(value * 1.15078)
}
/// Converts the supplied Knots value to Kilometres Per Hour
func (value Knots) ToKilometresPerHour() float64 { 
	return float64(value * 1.852)
}
/// Converts the supplied Knots value to Feet Per Second
func (value Knots) ToFeetPerSecond() float64 { 
	return float64(value * 1.68781)
}
/// Converts the supplied Knots value to Metres Per Second
func (value Knots) ToMetresPerSecond() float64 { 
	return float64(value / 1.94384)
}

/// Metres Per Second conversion functions
type MetresPerSecond float64

/// Converts the supplied Metres Per Second value to Miles Per Hour
func (value MetresPerSecond) ToMilesPerHour() float64 { 
	return float64(value * 2.23694)
}
/// Converts the supplied Metres Per Second value to Kilometres Per Hour
func (value MetresPerSecond) ToKilometresPerHour() float64 { 
	return float64(value * 3.6)
}
/// Converts the supplied Metres Per Second value to Feet Per Second
func (value MetresPerSecond) ToFeetPerSecond() float64 { 
	return float64(value * 3.28084)
}
/// Converts the supplied Metres Per Second value to Knots
func (value MetresPerSecond) ToKnots() float64 { 
	return float64(value * 1.94384)
}

/// Miles Per Hour conversion functions
type MilesPerHour float64

/// Converts the supplied Miles Per Hour value to Kilometres Per Hour
func (value MilesPerHour) ToKilometresPerHour() float64 { 
	return float64(value * 1.60934)
}
/// Converts the supplied Miles Per Hour value to Feet Per Second
func (value MilesPerHour) ToFeetPerSecond() float64 { 
	return float64(value * 1.46667)
}
/// Converts the supplied Miles Per Hour value to Metres Per Second
func (value MilesPerHour) ToMetresPerSecond() float64 { 
	return float64(value / 2.23694)
}
/// Converts the supplied Miles Per Hour value to Knots
func (value MilesPerHour) ToKnots() float64 { 
	return float64(value / 1.15078)
}
